name = "tokens"
main = "src/server/index.js"
compatibility_date = "2025-06-10"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "GRID_KV"
id = "81af810e9ebe44828bf2849609f0551a"

[triggers]
crons = ["0 0 * * 7"]
